### PR TITLE
Add pam-u2f

### PR DESCRIPTION
**Pull request by mrvdb**
Basically a test PR to see if I got the workflow right before I start pushing more.

PKGBUILD same as upstream, other than adding the 'powerpc64le' arch.

Just compiles/installs cleanly, using this on Talos II machine on daily basis.

### CODE REVIEW

**Comment by kth5** [comment]
My apologies but pretty busy with family matters these days so not much time for brainstorming. :')

Anyway, I was thinking of integrating CI to GitHub PRs that would build packages and make them available in a staging repo to be handpicked. This of course only from permitted accounts so that I won't be overrun by malicious shell code in PKGBUILDs. Maybe at first with a comment on a PR that triggers.

I have some experience doing this with Jenkins but I'm open to suggestions on how to achieve this and can provide build resources for all three architectures albeit only a 2x1Ghz for riscv64 which may make things a tad slow.

Once the packages are in staging, reviews should get the PR merged and the package rebuilt. The work on reproducable builds by the main Archlinux guys comes in handy here. I am however not sure how to compare and verify builds yet.

**Comment by mrvdb** [comment]
Some random thoughts:

- CI on PRs sounds like a good first step, is github the home to do it in?
- is https://mirror.grapentin.org/parabola-ports/ similar enough to combine some efforts?
- archlinux reproducible build work looks very interesting, but also a major effort to get started with? It makes helping out easier though, I bet running a rebuilderd instance would be something users would be willing to do.
- perhaps move the brainstorming out of this PR?

**Comment by mrvdb** [comment]
Anything needs doing for this PR? Just making sure you're not waiting for me. No rush.

**Comment by kth5** [comment]
It's been a while since I emailed you so not sure you received my email but yeah, I'll go ahead and merge this to testing in a bit.

**Pull request merged**
